base_url = "https://wags-1314.github.io"
compile_sass = true
build_search_index = false

title = "SolarPunk"

theme = "anemone"

taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = false

[extra]
default_theme = "light"

header_nav = [
	   { url = "/", name_en = "/home/" },
	   { url = "/cv", name_en = "/CV/" },
	   { url = "/blog", name_en = "/blog/" }
]
